CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role ENUM('ROLE_USER', 'ROLE_ADMIN') NOT NULL
);

CREATE TABLE token (
  id INT AUTO_INCREMENT PRIMARY KEY,
  token VARCHAR(255) NOT NULL UNIQUE,
  user_id INT NOT NULL,
  expiry_date TIMESTAMP NOT NULL,
  is_expired BOOLEAN NOT NULL,
  is_revoked BOOLEAN NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE demo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);